ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
        FallbackResource /index.php
    </Directory>

    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/var/www/html/public/$1
</VirtualHost>
